name: multiple jobs and manual trigger
on:
 push:
    branches:
        - '**'
    paths:
        - '**'
 workflow_dispatch: 
    inputs:
      run_job_3:
        description: 'job_3'
  

jobs:
    
    job_1: 
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/Dev-branch'
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: print husband name
          run: echo "venu Babu"

    job_2:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/STAGING'
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: print husband character
          run: echo "Venu Babu is a Donkey"
    
    job_3:
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch' 
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: print about Anuhya
          run: echo "Anuhya Koganti is a very very good and innocent"