name: workflow-beginner-Q1
on: push

jobs:
  echo_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Print date 1
      run: date 

  echo_job_2:
    runs-on: ubuntu-latest
    needs: echo_job_1
    steps:
    - name: print name
      run: echo "Venu is stupid"

