name: workflow-beginner-Q1
on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print date 1
      run: |
        date > date.txt
        cat date.txt

    - name: save the output
      uses: actions/upload-artifact@v3
      with:
        name: datefile
        path: date.txt

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: sleep
        run: sleep 10

  job_3:
    runs-on: ubuntu-latest
    needs: job_2
    steps:
    - name: download the output
      uses: actions/download-artifact@v3
      with:
        name: datefile

    - name: print previous output
      run: cat date.txt

